services:
  aarogyam-client:
    build: ./client/aarogyam-client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  api-gateway:
    build: ./server/aarogyam-api-gateway/nginx
    ports:
      - "80:80"
    volumes:
      - ./server/aarogyam-api-gateway/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main-service
    networks:
      - app-network

  main-service:
    build: ./server/aarogyam-server
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - BACKEND_URL=${BACKEND_URL}
      - BREVO_API_KEY=${BREVO_API_KEY}
    depends_on:
      - aarogyam-db
    networks:
      - app-network

  aarogyam-db:
    image: postgres:16.0
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - aarogyam_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  aarogyam_data:

networks:
  app-network:
    driver: bridge